<form method = "post" action = "<?= $action; ?>">
<div>
    <div>
      <label>Titulo</label>
    </div>
    <div>
      <input placeholder = "Titulo" name = "title"  value = "<?= empty($values["title"]) ? "" : $values["title"] ?>" />
    </div>
    <? if( !empty($errors["title"]) ) {?>
      <div>
        <p><?= implode(",", $errors["title"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <div>
      <label>Descripción</label>
    </div>
    <div>
      <input placeholder = "Descripción" name = "description" value = "<?= empty($values["description"]) ? "" : $values["description"] ?>" />
    </div>
    <? if( !empty($errors["description"]) ) {?>
      <div>
        <p><?= implode(",", $errors["description"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <div>
      <label>Prioridad</label>
    </div>
    <div>
      <select name = "priority" value = "<?= empty($values["priority"]) ? "" : $values["priority"] ?>">
        <option value = "baja">Baja</option>
        <option value = "media">Media</option>
        <option value = "alta">Alta</option>
      </select>
    </div>
    <? if( !empty($errors["priority"]) ) {?>
      <div>
        <p><?= implode(",", $errors["priority"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <div>
      <label>Vencimiento</label>
    </div>
    <div>
      <input
        type = "date"
        min = "<?= date("Y-m-d") ?>"
        name = "due_date"
        value = "<?= empty($values["due_date"]) ? "" : DateTime::createFromFormat("Y-m-d", $values["due_date"])->format("Y-m-d"); ?>"
      />
    </div>
    <? if( !empty($errors["due_date"]) ) {?>
      <div>
        <p><?= implode(",", $errors["due_date"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <div>
      <label>Estado</label>
    </div>
    <div>
      <select name = "status" value = "<?= empty($values["status"]) ? "" : $values["status"] ?>">
        <option value = "pendiente">Pendiente</option>
        <option value = "proceso">En proceso</option>
        <option value = "finalizada">Finalizada</option>
      </select>
    </div>
    <? if( !empty($errors["status"]) ) {?>
      <div>
        <p><?= implode(",", $errors["status"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <div>
      <label>Categoria</label>
    </div>
    <div>
      <select name = "category_id" value = "<?= empty($values["category_id"]) ? "" : $values["category_id"] ?>">
        <option value = ""></option>
        <? foreach($categorias as $category) { ?>
          <option value = "<?= $category->id; ?>"><?= $category->name; ?></option>
        <? } ?>
      </select>
    </div>
    <? if( !empty($errors["category_id"]) ) {?>
      <div>
        <p><?= implode(",", $errors["category_id"]); ?></p>
      </div>
    <? } ?>
  </div>
  <div>
    <button onclick ="history.go(-1);">Cancelar</button>
    <button type ="submit">Guardar</button>
  </div>
</form>
