<!DOCTYPE html>
<html lang="en">
<head>
    
    <title>tablas</title>
    <style> table, th, td{
        border: 1px solid black
    border-spacing: 10px;
    border-collapse: collapse;

    border: 1px solid black;

    padding: 8px;
  
    }
    </style>
</head>
<body>
   
    <center><h2>Tareas</h2>
    <table style=" width:500px">
        
        <tr>
            <th>Titulo</th>
        <th>Fecha de entrega</th>
            <th>Categorias</th>
            <th>Prioridad</th>
            <th>Estado</th>
            <th>Creado</th>
            <th>Actualizado</th>
            <th>Completado</th>

        
        
        
        
       
         </tr>
        
        
         <tr>
        <td colspan="1"> </td>
        </tr>
         <tr>
            <th rowspan="1"></th>
        </tr>
        <td rowspan="1"> </td>
        </tr>
        
         <tr>
        <td colspan="1"> </td>
        </tr>
         </tr>
        <tr>
        <td rowspan="1"> </td>
        </tr>
        
         <tr>
        <td colspan="1"> </td>
        </tr>
        
    </table></center>
</body>
</html>   
