<!DOCTYPE html>
<html lang="en">
<head>

    <title>tablas</title>
    <style> table, th, td{
        border: 1px solid black
    border-spacing: 10px;
    border-collapse: collapse;

    border: 1px solid black;

    padding: 8px;

    }
    </style>
</head>
<body>
  <center><h2>Tareas</h2></center>
  <table style=" width:100%;">
    <tr>
      <th>Titulo</th>
      <th>Fecha de entrega</th>
      <th>Categorias</th>
      <th>Prioridad</th>
      <th>Estado</th>
      <th>Creado</th>
      <th>Actualizado</th>
      <th>Completado</tr>
    </tr>
    <?php foreach($tareas as $tarea) { ?>
      <tr>
        <td><?= $tarea->title ?></td>
        <td><?= $tarea->due_date ?></td>
        <td><?= $tarea->categoria_nombre ?></td>
        <td><?= $tarea->priority ?></td>
        <td><?= $tarea->status ?></td>
        <td><?= $tarea->created_at ?></td>
        <td><?= $tarea->updated_at ?></td>
        <td><?= $tarea->completed_at ?></td>
      </tr>
    <?php }  ?>
  </table>

</body>
</html>
